### ISSUE TITLE
ProcessException: No such file or directory

### ISSUE THREAD

**Issue by shaunthegeek** [g1eny0ung/git_clone#1]
<img width="1179" alt="image" src="https://github.com/g1eny0ung/git_clone/assets/4971414/eb21a9b2-3a61-462b-9e57-2e73a031db93">

<img width="900" alt="image" src="https://github.com/g1eny0ung/git_clone/assets/4971414/8be94724-3aa9-42a6-920a-2de82466860e">

```
Flutter 3.16.9 • channel [user-branch] • unknown source
Framework • revision 41456452f2  • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

Software:

    System Software Overview:

      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Chip: Apple M1 Pro
```

**Comment by g1eny0ung** [comment]
I guess this is because I used `--` to split options and strings but it's only available in bash. I'll fix it now.

**Comment by shaunthegeek** [comment]
does this package depend local `git cli`?

maybe the reason is: Android Phone doesn't have `git cli`.

**Comment by g1eny0ung** [comment]
> does this package depend local `git cli`?
> 
> maybe the reason is: Android Phone doesn't have `git cli`.

Oh...yes, it is, this package relies on system side `git` and does not provide an embed `git` cli.

**Comment by g1eny0ung** [comment]
> I guess this is because I used `--` to split options and strings but it's only available in bash. I'll fix it now.

I believe I may have been mistaken earlier. The double-dash (`--`) convention is used in command-line interfaces to differentiate between command options and arguments. It is not a feature specific to one shell, but rather a convention that is widely adopted across various command-line tools.

**Comment by g1eny0ung** [comment]
I've created an issue that perhaps we can go and simulate the behavior of `git clone`.
